version: '3'
services:
  test-websites:
    build: ./
    image: test-websites
    container_name: test-websites
    restart: always
    ports:
      - 81:8080
      - 82:7860
    environment:
      BUCKET: ***
      AWS_DEFAULT_REGION: ***
      LUNCH: true
      GRADIO: true
      AWS_ACCESS_KEY_ID: ***
      AWS_SECRET_ACCESS_KEY: ***
    healthcheck:
      test: curl --fail http://localhost:8080/lunch && curl --fail http://localhost:7860/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s